$('.owl-carousel').owlCarousel({
    loop:true,
    margin:35,
    nav:false,
    dots:true,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:3
        },
        1000:{
            items:3
        }
    }
})